### ISSUE TITLE
What are the learned tokens L?

### ISSUE THREAD

**Issue by g-h-chen** [UCSC-VLAA/CLIPS#1]
Thanks for your work! I have a question on the learned tokens L. 

In fig1, the text decoder only takes image and webcaptions as inputs. But in eq8, a set of learnable tokens L is introduced to the loss. Is it acting as a set of soft prompts?

**Comment by Yanqing0327** [comment]
Thank you for your interest in our work!

Yes, exactly. Due to the asymmetric nature of text input and output in our design, we introduced a set of learnable tokens as input queries to the text decoder. These learnable tokens effectively act as soft prompts, helping the model adaptively generate outputs. Let me know if you have any further questions!
